### ISSUE TITLE
발전원별 잠재량 표시

### ISSUE THREAD

**Issue by Jeonwoojae** [web-eco-location/eco-location-back#17]

**Comment by Jeonwoojae** [comment]
### 해결 방법
- 연도와 발전원 타입을 입력받아 각 지역에 해당하는 잠재량 데이터를 반환한다.

API [GET] /energy-potential/source?sourceType={발전원 타입}&year={연도}

**Comment by NoMaL21** [comment]
다음은 강원대학교에 예측설비용량이 산출된 기준과 단위, 그리고 예측 에너지 잠재량의 단위에 대해서 질문한 것에 대한 답변입니다.

(1) 설비용량의 단위는 kW입니다. 산출된 기준은 확인 요청하였으며, 답변이 오면 메일 송부드리겠습니다.

(2) 잠재 발전 가능량의 단위는 Wh입니다.

추후 메일이 오면 또 코멘트해놓겠습니다.
