### ISSUE TITLE
재생에너지 전환율 표시 데이터 csv파일 저장

### ISSUE THREAD

**Issue by Jeonwoojae** [web-eco-location/eco-location-back#2]
## Issues 설명
데이터를 사용하기 위해 csv 파일을 저장 해야하는 문제 발생

**Comment by NoMaL21** [comment]
https://drive.google.com/file/d/1pCMuUeoTj6NkO_G8ESpbbv1BZb2BlN3Y/view?usp=share_link

발전설비량을 신재생에너지 합계/지역별 신재생에너지 비율로 확인할 수 있는 csv파일입니다.

**Comment by NoMaL21** [comment]
https://drive.google.com/file/d/1jRW7Y8viWreCYDDF4VCOaotVgewWa9W9/view?usp=share_link

표의 칼럼을 데이터베이스 설계에 맞게 고치고, 합계와 비율을 정리했고, ID값을 정리해놓은 csv파일입니다.

**Comment by NoMaL21** [comment]
https://drive.google.com/file/d/1nfk6ld2sNrB6DfgUjfULKVjeNXVwEYPv/view?usp=share_link

표의 칼럼의 오타를 고치고 ID값을 지운 csv파일입니다.
