### ISSUE TITLE
잠재량 csv파일에서 지역 일부분이 이상한 문제 발생 

### ISSUE THREAD

**Issue by Jeonwoojae** [web-eco-location/eco-location-back#33]
![image](https://github.com/web-eco-location/eco-location-back/assets/78198709/b9fa62dd-2f0e-433e-92c7-3d310813d229)

**Comment by MK5532** [comment]
https://drive.google.com/file/d/1UC8tur-hFdoHBCd1D3TfvuPl_BpoNZ0C/view?usp=share_link
유니코드 문제로 이름 깨짐 현상이 발생, 수정했습니다.
