### ISSUE TITLE
-from front 데이터 정제 요청

### ISSUE THREAD

**Issue by Parkybin** [web-eco-location/eco-location-back#41]
DB명 GENERATORS
"광역시도별"로 총합계를 나타내는 데이터가 필요합니다.
요구 속성: " 지역 이름 , 지역 내 발전량 총합, 발전원 "이외 자유
=> 광역시도(14) * 발전원(N) 개 만큼의 데이터
이유: 클라이언트쪽 로딩이 너무 길어짐

**Comment by MK5532** [comment]
사용 SQL 구문
SELECT WIDE_AREA as area_Name, power_source, sum(GENERATE_AMOUNT) as generate_amount FROM GENERATORS where not power_source in ('석탄', '가스', '') group by WIDE_AREA, power_source;

**Comment by Jeonwoojae** [comment]
response 
```
지역이름, 에너지종류, 발전량
```
